{{- if not .Values.database.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotrs.fullname" . }}-database
  labels:
    {{- include "gotrs.database.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $dbAnnotations := eq .Values.database.type "mysql" | ternary (.Values.database.mysql.serviceAnnotations | default dict) (.Values.database.postgresql.serviceAnnotations | default dict) }}
  {{- $annotations := merge $dbAnnotations (.Values.global.commonAnnotations | default dict) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    {{- if eq .Values.database.type "mysql" }}
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
    {{- else }}
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
    {{- end }}
  selector:
    {{- include "gotrs.database.selectorLabels" . | nindent 4 }}
{{- end }}
